#!/bin/bash
#
#

function popd
{
    if [ -n "$DIR_STACK" ]; then
        DIR_STACK=${DIR_STACK#* }
        cd ${DIR_STACK%% *}
        echo "$PWD" 
    else
        echo "stack is empty, still in $PWD"
    fi
}