#! /bin/bash 
# task 4-2
# use different utility convert to pnm first, then convert pnm ot jpeg
# the usage of case is to select the correct conversion utility based on file extension
# ltbs on page 358 parenthesis is separated from pattern in a new line, is not acceptable.
# case expression in 
#   pattern1)
#   statements ;;
#   *)
#   statements ;;
# esac
# https://filesamples.com/categories/image

usage="Usage: $0 [-s size] [-w width] [-c \"color\"] imagefile ..."

function procimage () {
    filename=$1
    size=${2:-480}
    width=${3:-2}
    color=${4:-"-color red"}
    filename=${filename:?" required"}
    extension=${filename##*.}
    # .pnm is not acceptable on mac, will prompt error reading first byte of what is expected to be a Netpbm magic number.
    # ltbs has inconsistent code on page 332 page 359
    pnmfile=${filename%.*}.ppm
    jpegfile=${filename%.*}.jpeg
    # select correct conversion utility based on file extension, use miscellaneous utility convert graphic file to common ppm file
    case $extension in 
        jpeg|jpg)
        echo "$filename already jpeg file, no need to convert" 
        return 0;;
        tga)
        tgatoppm  $filename > $pnmfile;;
        xpm)
        xpmtoppm $filename > $pnmfile;;
        pcx)
        pcxtoppm $filename > $pnmfile;;
        tiff|tif)
        tifftopnm $filename > $pnmfile;;
        gif)
        giftopnm $filename > $pnmfile;;
        *)
        echo "$filename has unknown graphic file extension $extension"
        return 1;;
    esac

    pnmscale -quiet -xysize $size $size $pnmfile |
    pnmmargin $color $width |
    pnmtojpeg > $jpegfile

    rm $pnmfile
}

while getopts ":s:w:c:" opt; do 
    case $opt in 
        s) 
            size=$OPTARG ;;
        w)
            width=$OPTARG ;;
        c)  
            color="-color $OPTARG" ;;
        \?) 
            echo $usage
            exit 1;;
    esac
done

shift $((OPTIND-1))
# $* is single string while $@ is "$1" "$2" ... "$N", 
# -z "$@" would complain too many arguments if you pass multiple file, 
# even if you pass only * or *.*, when command ./tojpeg -s 360 -w 10 -c purple *.* doing path expansion,
# they usualy expands to multiple arguemnt, in *.* case, it expands to all files with extension
# after path expansino, it search for command in this case, tojpeg is neither function builtin nor command in path
if [ -z "$*" ]; then 
    echo $usage
fi

for imagefile in "$@"; do
    # double quote around color is necessary, otherwise it would complain on step pnmmargin
    procimage $imagefile $size $width "$color"
done
