#!/bin/bash
# make fileinfo under file_attribute_operator/ accept multipe arguments
# usage: ./fileinfomultiargu *

function finfo (){
    filename="$1"
    if ! [ -e "$filename" ]; then 
        echo "$filename doesn't exist"
        #exit 1 in original fileinfo script is not acceptable, as it exit immediatley from subshell of this scirpt, so other arguments from script dont get a chance to process,
        return 1
    fi

    if [ -f "$filename" ]; then 
        echo "$filename is a regular file"
    elif [ -d "$filename" ]; then
        echo -n "$filename is a directory could "
        if ! [ -x "$filename" ]; then 
            echo -n "not "
        fi
        echo "be searched"
    else 
        echo "$filename is not a regular file nor a directory"
    fi

    if [ -O "$filename" ]; then 
        echo "$filename is owned by you"
    fi 

    if [ -r "$filename" ]; then 
        echo "$filename is readable"
    fi

    if [ -w "$filename" ]; then
        echo "$filename is writable"
    fi 

    if [ -x "$filename" -a ! -d "$filename" ]; then
        echo "$filename is executable"
    fi
}

#finfo nonexist
for filename in "$@"
do  
    finfo $filename
    echo
done