#!/bin/bash
# use time recls * compare with time tracels *, this one is one magnitude faster
# real	0m0.075s
# user	0m0.027s
# sys	0m0.041s
function recls () {
    singletab="|\t"
    pipedash="|-------"
    tab=$singletab
    echo "."
    echo -e $singletab
    for tryfile in "$@"
    do 
        if [ -d $tryfile ]; then
            echo -e $pipedash$tryfile/
            echo -e $tab"|"
        else 
            echo -e $pipedash$tryfile
            echo -e $tab"|"
        fi
        if [ -d "$tryfile" ]; then
            thisfile=$tryfile
            recdir $(command ls $tryfile)
        fi
    done
}

function recdir () {
    #this is local, it could get correct value based on tab's value
    local tabwithdash=$tab$pipedash
    tab=$tab$singletab
    for file in "$@"
    do 
        thisfile=$thisfile/$file
        if [ -d $thisfile ]; then
            echo -e $tabwithdash$file/
            echo -e $tab"|"
        else 
            echo -e $tabwithdash$file
        fi
        # echo "thisfile now is $thisfile"
        if [ -d "$thisfile" ]; then
            # echo "thisfile $thisfile is directory"
            # recdir thisfile will endup only one level from main script argument
            # either for file in $(ls $1), recdir thisfile,
            # or for file in $@, recdir $(ls thisfile) 
            recdir $(ls "$thisfile")
        fi
        thisfile=${thisfile%/*}
    done
    tab=${tab%"$singletab"}
    #order of print and shrink is important, just litke order  of tabwithdash and tab
    echo -e $tab
}